### ISSUE TITLE
PHP7.4 build with igbinary enabled fails due to missing headers

### ISSUE THREAD

**Issue by nrocy** [Planerio/aws-elasticache-cluster-client-build#6]
First up, thanks for putting this tooling together, massively appreciated.

Following the README, the below build fails during PHP module compilation due to missing igbinary.h:

`docker build -f Dockerfile.debian --iidfile=/tmp/elasticache.docker --build-arg PHP_VERSION=7.4 --build-arg ENABLE_IGBINARY=1 .`

The same build worked on commit 3358e67958978c9d4cf2fa74b08ccff7f8d8adfc

From what I can tell, the attached diff seems to fix it, but can't speak to whether it's the correct fix (hence no PR)

[maybe-fix.diff.txt](https://github.com/Planerio/aws-elasticache-cluster-client-build/files/6311288/maybe-fix.diff.txt)

**Comment by nrocy** [comment]
To follow up on this: while it does actually build, the module API is the wrong version, will keep digging.

**Comment by KiNgMaR** [comment]
Thanks for the feedback :)

Can you try this branch? https://github.com/Planerio/aws-elasticache-cluster-client-build/tree/bugfix/issue-6

**Comment by nrocy** [comment]
@KiNgMaR absolutely! will feedback shortly

**Comment by nrocy** [comment]
@KiNgMaR seems to work a treat - thank you!

**Comment by KiNgMaR** [comment]
Cool!
